Repository Crimson-Vision/Libriscan, pull requests merged in 2025-10, with the labels that each got.

#100 Feature/91 98 textblock enhancements
  libriscan/biblios/admin.py
  libriscan/biblios/migrations/0017_textblock_suggestions.py
  libriscan/biblios/models.py
  libriscan/biblios/services/extractors.py
  libriscan/biblios/services/suggestions.py
Labels: Back End

#105 Add push action
  .github/workflows/docker-publish.yml
Labels: Infrastructure

#106 Additional Docker image tags
  .github/workflows/docker-publish.yml
Labels: Infrastructure

#107 Remove env vars, add Caddy
  sample-config/compose.yaml
Labels: Infrastructure

#104 Feature/34 url structure
  libriscan/biblios/admin.py
  libriscan/biblios/fixtures/collections.json
  libriscan/biblios/fixtures/series.json
  libriscan/biblios/migrations/0018_collection_slug_consortium_slug_series_slug_and_more.py
  libriscan/biblios/migrations/0019_alter_collection_owner_alter_document_series_and_more.py
  libriscan/biblios/models.py
  libriscan/biblios/services/exporters.py
  libriscan/biblios/services/extractors.py
  libriscan/biblios/templates/biblios/collection_detail.html
  libriscan/biblios/templates/biblios/document_detail.html
  libriscan/biblios/templates/biblios/organization_detail.html
  libriscan/biblios/templates/biblios/organization_list.html
  libriscan/biblios/templates/biblios/page.html
  libriscan/biblios/templates/biblios/series_detail.html
  libriscan/biblios/tests/test_extractors.py
  libriscan/biblios/urls.py
  libriscan/biblios/views.py
Labels: Back End

#110 Feature/57 Upload Image
  libriscan/biblios/forms.py
  libriscan/biblios/templates/biblios/base.html
  libriscan/biblios/templates/biblios/components/forms/file_upload.html
  libriscan/biblios/templates/biblios/scan.html
  libriscan/biblios/urls.py
  libriscan/biblios/views.py
  libriscan/libriscan/settings.py
Labels: Front End

#117 Move gunicorn config to conf file, with sample
  libriscan/entrypoint.sh
  sample-config/gunicorn.conf.py
Labels: Infrastructure

#116 [Feature] UI Enhance Details Page of Organization > Collection > Series > Document
  libriscan/biblios/templates/biblios/base.html
  libriscan/biblios/templates/biblios/collection_detail.html
  libriscan/biblios/templates/biblios/components/layout/hero_section.html
  libriscan/biblios/templates/biblios/components/navigation/navbar.html
  libriscan/biblios/templates/biblios/consortium_detail.html
  libriscan/biblios/templates/biblios/document_form.html
  libriscan/biblios/templates/biblios/organization_detail.html
  libriscan/biblios/templates/biblios/organization_list.html
  libriscan/biblios/templates/biblios/series_detail.html
  libriscan/biblios/views.py
Labels: enhancement, Front End
